### ISSUE TITLE
"hostAddon.cacheKeyForTree is not a function 

### ISSUE THREAD

**Issue by bbtb1982** [ember-engines/ember-engines#435] opened 2017-06-13 19:15 UTC
We're getting this error when building our project with v5.5 - v5.8 version 5.4 builds fine.

hostAddon.cacheKeyForTree is not a function
TypeError: hostAddon.cacheKeyForTree is not a function
    at .../node_modules/ember-engines/lib/engine-addon.js:382:49
    at Array.map (native)
    at Class.options.nonDuplicatedAddonInvoke (.../ember-deployment/node_modules/ember-engines/lib/engine-addon.js:372:26)
    at Class.buildVendorTree (.../node_modules/ember-engines/lib/engine-addon.js:129:36)
    at Class._memoize (.../node_modules/ember-engines/lib/utils/memoize.js:10:38)
    at Class.buildCompleteJSTree (.../node_modules/ember-engines/lib/engine-addon.js:255:36)
    at Class._memoize (.../node_modules/ember-engines/lib/utils/memoize.js:10:38)
    at Class.treeForEngine (.../node_modules/ember-engines/lib/engine-addon.js:540:50)
    at Class.treeFor (.../node_modules/ember-engines/lib/engine-addon.js:928:25)

here is our NPM dependencies

  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-cli": "2.12.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-cdn": "2.1.0",
    "ember-cli-content-security-policy": "0.6.1",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-deploy": "^1.0.0",
    "ember-cli-deploy-build": "^1.0.0",
    "ember-cli-deploy-display-revisions": "^1.0.0",
    "ember-cli-deploy-gzip": "^1.0.0",
    "ember-cli-deploy-revision-data": "^1.0.0",
    "ember-cli-deploy-s3": "^1.0.0",
    "ember-cli-deploy-s3-index": "^1.0.0",
    "ember-cli-deploy-slack": "^1.0.0",
    "ember-cli-document-title": "0.3.3",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-g-maps": "0.5.10",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-mirage": "0.1.13",
    "ember-cli-qunit": "^3.1.0",
    "ember-cli-sass": "~6.1.1",
    "ember-cli-selectize": "enderlabs/ember-cli-selectize.git#v0.4.5",
    "ember-cli-sentry": "2.4.3",
    "ember-cli-shims": "^1.0.2",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-sticky": "0.6.2",
    "ember-cli-uglify": "^1.2.0",
    "ember-concurrency": "~0.8.1",
    "ember-data": "2.12.1",
    "ember-data-model-fragments": "2.11.2",
    "ember-engines": "^0.5.0",
    "ember-export-application-global": "^1.0.5",
    "ember-inflector": "1.11.0",
    "ember-load-initializers": "^0.6.0",
    "ember-local-storage": "~1.3.6",
    "ember-metrics": "0.10.0",
    "ember-modal-dialog": "v2.0.0-beta.0",
    "ember-power-select": "~1.7.0",
    "ember-power-select-with-create": "~0.4.3",
    "ember-resolver": "^2.0.3",
    "ember-source": "~2.12.0",
    "ember-tether": "0.4.1",
    "ember-toastr": "~1.5.0",
    "ember-tooltips": "2.9.0-beta.0",
    "ember-truth-helpers": "^1.3.0",
    "ember-validations": "2.0.0-alpha.5",
    "ember-wormhole": "~0.5.1",
    "liquid-fire": "~0.27.0",
    "loader.js": "^4.2.3"
  },
  "dependencies": {
    [... removed internal addons ]
    "ember-engines": "^0.5.0",
picker.git#~v1.0.0"
  }

p.s. Thank you very much for all your contributions. The effort we are able to leverage and use is amazing. It empowers and employs us.

**Comment by tomoguisuru** [comment] 2017-06-14 03:14
I should add that this happening with a lazy loaded engine

**Comment by rwjblue** [comment] 2017-06-14 03:54
I believe that the issue is that`cacheKeyForTree` is only added in ember-cli@2.13+.

**Comment by peStoney** [comment] 2017-08-17 14:26
@rwjblue This also happens in our case with a lazy loading engine and ember-cli 2.12.0.

**Comment by rwjblue** [comment] 2017-08-17 16:03
Yep, we need to guard the invocation of `cacheKeyForTree` (if not present on an `addon` we would default to no caching).

**Comment by peStoney** [comment] 2017-08-18 07:31
@rwjblue I did dig a little bit into  the calculate-cache-key-for-tree Addon - if I got the concept right it makes total sense to avoid redundancies. I just have no clue how to utilize the Addon - documentation is sparse...

**Comment by rwjblue** [comment] 2017-08-21 19:12
Fixed by #469

**Closed by rwjblue** 2017-08-21 19:12 UTC
Labels: bug

**Comment by akashdsouza** [comment] 2017-08-21 19:58
@peStoney may be you start with how it's been used here: https://github.com/ember-engines/ember-engines/blob/master/lib/engine-addon.js#L319

**Comment by peStoney** [comment] 2017-08-22 07:17
@akashdsouza Thanks! I think I'm getting it - actually every addon used in an engine needs to implement `cachKeyForTree()`. Is this correct?

**Comment by trentmwillis** [comment] 2017-08-27 19:07
@peStoney the `EmberAddon` base class implements `cacheKeyForTree` by default. So as long as you're on a version of Ember-CLI that has `cacheKeyForTree`, all addons will have it by default. That said, addons that customize any of the `treeFor` hooks would want to reimplement the `cacheKeyForTree` hook to opt back in to caching.

For more details and background, check out the RFC for that hook: https://github.com/ember-cli/rfcs/blob/master/complete/0090-addon-tree-caching.md
