### ISSUE TITLE
route#refresh no longer works

### ISSUE THREAD

**Issue by amk221** [ember-engines/ember-engines#614] opened 2019-01-15 10:38 UTC
App demoing that `this.refresh()` in an engine route works in ember 3.5.1, but not ember 3.6

Never calls model hook: https://github.com/amk221/-ember-engine-refresh-route/commit/71dd1b606e5a33d01ede516aa6936bc5b2683b1d#diff-394600f34d48dad6f0abc29af03d8b1bR5

**Comment by villander** [comment] 2019-01-15 13:34
@amk221 update this project to `0.5.26` and try again please?

**Comment by amk221** [comment] 2019-01-15 14:04
Yeah, still an issue

**Comment by villander** [comment] 2019-01-15 14:05
Ok, I'll take a look

**Comment by thec0keman** [comment] 2019-01-17 16:48
This may be related, but after upgrading from Ember 3.5 -> 3.6 or 3.7, setting query params is calling a `Maximum call stack size exceeded`.

For example:
```
Route:
  queryParams: {
    sent: {
      refreshModel: true
    }
  }
  ...

Controller:
  queryParams: ['sent_filter'],

  sent: false,

  actions: {
    switchTabs(type) {
       set(this, 'sent', true);
    },
  }
```

Calling that action will call an infinite loop involving the `refresh` hook: 
```
hrsc-vendor.js:35155 Uncaught RangeError: Maximum call stack size exceeded
    at new Transition (hrsc-vendor.js:61723)
    at PrivateRouter.transitionByIntent (hrsc-vendor.js:62708)
    at PrivateRouter.refresh (hrsc-vendor.js:63239)
    at Class.refresh (hrsc-vendor.js:31329)
    at Class.queryParamsDidChange (hrsc-vendor.js:32600)
    at Class.triggerEvent (hrsc-vendor.js:33853)
    at PrivateRouter.triggerEvent (hrsc-vendor.js:32951)
    at PrivateRouter.fireQueryParamDidChange (hrsc-vendor.js:62944)
    at PrivateRouter.queryParamsTransition (hrsc-vendor.js:62676)
    at PrivateRouter.getTransitionByIntent (hrsc-vendor.js:62748)
```

This happens both with Ember.set and `transitionToRoute`.  It only occurs within engines.
(On 0.5.26)

I'd be happy to submit a separate issue if you'd prefer.

**Comment by XaserAcheron** [comment] 2019-01-29 18:07
Ran into this myself, so I did some digging and found the problem -- I'm not used to debugging Ember itself so apologies in advance if I fudge the explanation/terms a bit.

The tricky bit is [here](https://github.com/tildeio/router.js/blob/f385d1162ab3307c166bf5b6b19eef45345dd8d0/lib/router/transition-intent/named-transition-intent.ts#L61), in router.js's NamedTransitionIntent class:

```js
    // ...

    // Pivot handlers are provided for refresh transitions
    if (this.pivotHandler) {
      for (i = 0, len = parsedHandlers.length; i < len; ++i) {
        if (parsedHandlers[i].handler === this.pivotHandler.routeName) {
          invalidateIndex = i;
          break;
        }
      }
    }

    // ...
```

What's happening is `parsedHandlers` uses the _full_ route name, like so:

![pivothandler-welp1](https://user-images.githubusercontent.com/4601589/51929359-a70dc780-23bd-11e9-847e-d6b33a0374fe.png)

...but it's comparing it to `pivotHandler.routeName`, which is the _relative_ name of the route in Engine-land:

![pivothandler-welp2](https://user-images.githubusercontent.com/4601589/51929446-dde3dd80-23bd-11e9-8f14-152d94748a7b.png)

[Apologies for the shoddy screenshots. In the 2nd screen, fullRouteName is "home.tenant.analytics.interact"]

For `ember-engines` we need to compare it to `pivotHandler.fullRouteName` instead. I did a quick-hack fix in my local dev environment and confirmed that this fixes the issue (and the infinite loop @thec0keman found -- it's indeed the same root issue).

Since `fullRouteName` is an `ember-engines`-specific extension, it'll probably be necessary to extend NamedTransitionIntent to do this, I presume? Might be best to get a second opinion from a proper dev before attempting a PR just yet.

**Comment by amk221** [comment] 2019-01-29 18:36
Thanks for the debugging @XaserAcheron! This is a blocker for us upgrading, so appreciated!

**Comment by villander** [comment] 2019-01-29 18:37
thank you so much @XaserAcheron I think that we need upgrade ember-source on ember-engines...and it's will be fixed automatically, what about?

**Comment by villander** [comment] 2019-01-30 15:22
@XaserAcheron  where can we see the changes in ember route 3.7? changelog, diff etc.

**Comment by XaserAcheron** [comment] 2019-01-30 15:35
Sorry, I'm not following. I think we're on two different pages here.

**Comment by villander** [comment] 2019-01-30 17:22
I'm just asking if what changed from route 3.5 to 3.7, what changed in the API so I can help too

**Comment by svsalvador** [comment] 2019-02-04 12:49
I've found the same problem in my application upgrading to Ember 3.7 from 3.4. Any news?

**Comment by XaserAcheron** [comment] 2019-02-04 20:23
As a for-the-record, I'm tinkering with this, though this is one of those weird issues where it's technically easy to hack in a solution, but (probably?) difficult to solve "properly".

I've got a PR open for `router_js` now, but no guarantees it'll make it in as-is. It's mostly just a springboard for discussion.

**Comment by chadhietala** [comment] 2019-03-07 16:56
Is it possible that some one could write the failing test? I don't know too much about engines and it would help me a lot to address the issue.

**Comment by villander** [comment] 2019-03-26 14:45
@chadhietala  - this is the reproduction - https://github.com/amk221/-ember-engine-refresh-route/commit/71dd1b606e5a33d01ede516aa6936bc5b2683b1d#diff-394600f34d48dad6f0abc29af03d8b1bR5

**Comment by villander** [comment] 2019-03-27 01:09
@buschtoens @dgeb @stefanpenner Did anyone of you have this error in the big app that currently work on your companies?

**Comment by chadhietala** [comment] 2019-03-27 13:04
I have a fix here https://github.com/tildeio/router.js/pull/284

**Comment by villander** [comment] 2019-03-27 13:08
thanks - great stuff @chadhietala 😄

**Comment by chadhietala** [comment] 2019-03-29 17:12
Can someone please try the `release`, `beta`, or `canary` channel to see if we can close this issue? tildeio/router.js#284 fixed the reproduction by @amk221.

**Comment by amk221** [comment] 2019-04-02 10:45
Tried with `ember-source 3.9.0` and works 👌

**Comment by villander** [comment] 2019-04-02 11:22
awesome, thanks @chadhietala.

@amk221 can you close this issue, please?

**Closed** 2019-04-02 11:31 UTC
