### ISSUE TITLE
Components generated after server start are not being resolved

### ISSUE THREAD

**Issue by astronomersiva** [ember-engines/ember-engines#542] opened 2018-04-16 12:40 UTC
If a component is generated after server startup, it is not being resolved resulting in failed assertions.

[Reproduction link](https://github.com/astronomersiva/engine-reload) - This is basically a "Hello, World!" app. Run `ember server` and then do `ember g component after-server-start -ir my-engine`. 

Navigating to [http://localhost:4200/my-engine/hello](http://localhost:4200/my-engine/hello) will now throw:

`Assertion Failed: A component or helper named "after-server-start" could not be found`.

The assertion goes away if you restart the server. 

If one does not know that this issue can be solved by a simple server restart, it becomes extremely confusing as to why the error is being thrown in the first place.  It is also very inconvenient when working on slightly big applications as you are forced to wait for 20-30 seconds for the server to start each time a new component is generated.

Would love to help you fix this if you help me with where to look :)

**Comment by catz** [comment] 2018-04-23 09:46
+1 I'm getting similar errors very often.

**Comment by catz** [comment] 2018-10-17 14:55
similar to #577

**Comment by bertdeblock** [comment] 2021-03-11 12:30
Couldn't reproduce this in a brand new engine, so I think this is resolved and we can close this ticket.

**Closed** 2021-03-16 14:42 UTC
