### ISSUE TITLE
Re-Exporting from In-Repo-Engine

### ISSUE THREAD

**Issue by John0x** [ember-engines/ember-engines#315] opened 2017-01-14 16:23 UTC
Hey, I have a project which uses ember-paper and therefore has it imported correctly.
I've then generated an in-repo-engine for my admin panel (using ``ember g in-repo-engine admin``).

The content of the lib/admin/index.js is the following:
````javascript
var EngineAddon = require('ember-engines/lib/engine-addon');

module.exports = EngineAddon.extend({
  name: 'admin',

  isDevelopingAddon: function() {
    return true;
  }
});
````

As stated in the guide (http://ember-engines.com/guide/sharing-components-and-more) this should be sufficent to re-export all addons used by the project/owner. Though I get an ``A component or helper named "paper-button" could not be found`` error everytime I want to use one of the ember components in the engine.

**Comment by trentmwillis** [comment] 2017-01-14 17:10
I think this is a wording issue, we should update the last sentence to say:

> Now, any addon included in your **Engine's** package.json file will automatically get included in your Engine.

If you add `ember-paper` to `lib/admin/package.json` I believe it should work for you based on your description.

**Comment by John0x** [comment] 2017-01-14 17:12
@trentmwillis but in other issues it is stated, that only the projects/owner package.json need to have the dependencies listed?

See: https://github.com/ember-cli/ember-cli/issues/4164
"If a given dep exists in the project's package.json they are available in the in repo addon (regardless of if the in-repo-addon's package.json lists the dep)."

**Comment by trentmwillis** [comment] 2017-01-14 17:18
That's talking about a separate issue. You don't need to **install** the dependencies in the in-repo-addon/engine because Node's resolver will find the one installed in the root of the application. You still must list them in order for them to be imported into the application though. Ember-CLI uses the `package.json` to determine build time info.

In other words, that issue is about installation whereas this question is actually related to the build.

**Comment by John0x** [comment] 2017-01-14 17:34
Okay, thank you.
I've added the ember-paper to the package.json and it seems to find the component now, but there are some problems with bower assets apparently.

It cannot find hammer.js:
````
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat 'D:\development\client\tmp\source_map_concat-input_base_path-Jh0u0usL.tmp\undefined\hammer.js\hammer.js'
````

**Comment by knownasilya** [comment] 2017-01-14 18:10
You need to copy those from the parent bower.json as well

**Comment by John0x** [comment] 2017-01-14 20:36
@knownasilya that doesn't change a thing. Still the same error :/

I've copied the bower.json from the parent projekt into the root (besides the package.json) and changed the name attribute inside of it.

**Comment by knownasilya** [comment] 2017-01-14 21:04
Actually I just checked one of my projects and the bower.json should stay at the parent. Make sure that hammer is defined in there, if not, run `ember g ember-paper`.

**Comment by John0x** [comment] 2017-01-14 21:33
@knownasilya It does still not work :/

Parent package.json:
````json
{
  "name": "client",
  "version": "0.0.0",
  "description": "Small description for client goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "dependencies": {
    "ember-component-css": "0.2.8"
  },
  "devDependencies": {
    "@types/ember": "^2.7.36",
    "broccoli-asset-rev": "^2.5.0",
    "ember-ajax": "^2.5.3",
    "ember-can": "0.8.1",
    "ember-cli": "2.11.0-beta.1",
    "ember-cli-app-version": "^2.0.1",
    "ember-cli-babel": "^5.2.1",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-document-title": "0.3.3",
    "ember-cli-eslint": "3.0.2",
    "ember-cli-fastboot": "1.0.0-beta.13",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.6",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^3.1.0",
    "ember-cli-release": "^1.0.0-beta.2",
    "ember-cli-sass": "6.1.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-test-loader": "^1.1.1",
    "ember-cli-tree-shake": "^0.1.1",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.11.0",
    "ember-devtools": "^5.1.1",
    "ember-engines": "0.5.0-beta.4",
    "ember-export-application-global": "^1.1.1",
    "ember-intl": "2.18.0",
    "ember-load-initializers": "^0.6.3",
    "ember-network": "0.3.1",
    "ember-paper": "1.0.0-alpha.14",
    "ember-resolver": "^2.1.1",
    "ember-route-action-helper": "2.0.1",
    "ember-simple-auth": "1.2.0-beta.1",
    "ember-source": "^2.11.0-beta.2",
    "ember-transition-helper": "0.0.6",
    "ember-truth-helpers": "1.3.0",
    "loader.js": "^4.1.0"
  },
  "engines": {
    "node": ">= 0.12.0"
  },
  "private": true,
  "ember-addon": {
    "paths": [
      "lib/admin"
    ]
  }
}
````

Parent bower.json:

````json
{
  "name": "client",
  "dependencies": {
    "hammer.js": "^2.0.8",
    "matchMedia": "0.2.0"
  }
}
````

Engine package.json:
````json
{
  "name": "admin",
  "keywords": [
    "ember-addon",
    "ember-engine"
  ],
  "dependencies": {
    "ember-cli-htmlbars": "*",
    "ember-cli-babel": "*",
    "ember-paper": "1.0.0-alpha.14"
  }
}
````

**Comment by knownasilya** [comment] 2017-01-14 21:55
Sounds like a bug. I'm assuming you did `bower install` too.

**Comment by John0x** [comment] 2017-01-15 10:31
@knownasilya yes, I did.

**Comment by rwjblue** [comment] 2017-01-15 13:30
Can you throw a simple reproduction repo up that we could test things out on?

**Comment by John0x** [comment] 2017-01-15 16:21
@rwjblue sure, here you go:
https://github.com/John0x/ember-engines-repro

**Comment by knownasilya** [comment] 2017-01-18 18:56
Also broken in 0.4.0

**Comment by knownasilya** [comment] 2017-01-18 18:56
cc @miguelcobain

**Comment by nathanhammond** [comment] 2017-01-18 19:20
Bug is here: https://github.com/miguelcobain/ember-paper/blob/master/index.js#L34

Closing as this will be an `ember-paper` issue.

**Closed by nathanhammond** 2017-01-18 19:20 UTC

**Comment by knownasilya** [comment] 2017-01-18 19:32
Thanks for looking at this @nathanhammond.
@miguelcobain is working on https://github.com/miguelcobain/ember-paper/pull/594 which should solve this.

**Comment by John0x** [comment] 2017-01-19 07:14
Great, thank you guys :)

**Comment by rmachielse** [comment] 2017-03-23 21:36
We are having a similar problem with an internal addon that is depending on a bower package.
It looks like the `included` hook on the addon is also called for the engine, however `app.bowerDirectory` is `undefined` then, leading to the above error (it's looking for a file in the `undefined` folder).

In case of ember-paper it seems to be solved by using npm instead of bower. Isn't it possible to import bower components from addons on engines?

**Comment by nickschot** [comment] 2017-04-17 12:58
@rmachielse I think semantic-ui-ember has a similar issue. Did you solve this already?

**Comment by rmachielse** [comment] 2017-04-17 18:56
@nickschot we're moving away from bower the same way that ember-paper did
