### ISSUE TITLE
Lazily loaded in-repo-engine's buildRoutes is never called

### ISSUE THREAD

**Issue by xm** [ember-engines/ember-engines#363] opened 2017-03-18 01:44 UTC
Ember CLI: 2.12.0
Ember: 2.12.0
Ember Engines: 0.5.0-beta.10

As the title suggests, a lazily loaded engine's buildRoutes in lib/engine/addon/routes.js is never called. This breaks lazily loaded engines.

Example repo with the issue: https://github.com/xm/lazy-engines-test

**Comment by trentmwillis** [comment] 2017-03-18 02:03
The root cause of this is the same as https://github.com/ember-engines/ember-engines/issues/362. I'm gonna close this as a duplicate, but feel free to chime in or just subscribe to the other issue. I'm working on a fix for it.

**Closed by trentmwillis** 2017-03-18 02:03 UTC
