### ISSUE TITLE
Error when building for fastboot

### ISSUE THREAD

**Issue by cibernox** [ember-engines/ember-engines#262] opened 2016-11-17 15:14 UTC
I created a demo app for migrating to engines in a talk and I found an incompatibility running fastboot on the enginified version (it works without engines).

The error:
```
⠇ BuildingThe Broccoli Plugin: [AssetManifestGenerator: Asset Manifest Generator] failed with:
Error: Attempting to add bundle "parents-engine" to manifest but a bundle with that name already exists.
    at /Users/miguelcamba/code/engines-demos/smhw-blog/node_modules/ember-asset-loader/lib/asset-manifest-generator.js:83:15
    at Array.reduce (native)
    at AssetManifestGenerator.build (/Users/miguelcamba/code/engines-demos/smhw-blog/node_modules/ember-asset-loader/lib/asset-manifest-generator.js:72:34)
    at /Users/miguelcamba/code/engines-demos/smhw-blog/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/miguelcamba/code/engines-demos/smhw-blog/node_modules/rsvp/dist/rsvp.js:538:12)
```

Versions:
- Node 6
- "ember": "~2.10.0-beta.3",
- "ember-engines": "0.4.0-beta.3"
- lazyLoading: Tried with both, same error.

Reproduction:
- Clone https://github.com/mysencare/smhw-ember-engines-demo, branch `engines`.
- Install `ember-cli-fastboot` and run `ember fastboot --serve-assets`

**Comment by trentmwillis** [comment] 2016-11-19 23:25
@cibernox did you ever get this working? As far as I know, no one has really investigated what needs to be done in this area.

We have integration with a FastBoot-like environment at LI, but not FastBoot itself.

**Comment by cibernox** [comment] 2016-11-19 23:59
Nope, I was preparing a demo and thought about dropping fastboot but found this. My knowledge of  build pipeline is rather limited, but I'll check if at least I can give a better explanation of what exactly is failing and why.

**Comment by mike-north** [comment] 2016-11-20 13:07
I'm seeing this problem only when using fastboot with lazy engines. @cibernox do you have a version number or SHA I can test?

**Comment by cibernox** [comment] 2016-11-20 15:39
@mike-north you're right, I don't see it now if I disable lazyLoading. Perhaps when I tried it I didn't delete the /tmp folder.
Now I get a different error in non-lazy mode, but I suspect that it might have to do with my upgrade to node 7.1.

```
(node:62125) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:62125) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:62125) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:82
        throw backtrace;
        ^

Error: ENOTEMPTY: directory not empty, rmdir '/Users/miguelcamba/code/engines-demos/smhw-ember-engines-demo/dist/node_modules/moment/src/locale/'
    at rethrow (fs.js:77:21)
    at maybeCallback (fs.js:95:42)
    at Object.fs.rmdir (fs.js:801:14)
    at FSMonitor._measure (/Users/miguelcamba/code/engines-demos/smhw-ember-engines-demo/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.rmdir (/Users/miguelcamba/code/engines-demos/smhw-ember-engines-demo/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at TreeSync.<anonymous> (/Users/miguelcamba/code/engines-demos/smhw-ember-engines-demo/node_modules/tree-sync/index.js:80:19)
    at Array.forEach (native)
    at TreeSync.sync (/Users/miguelcamba/code/engines-demos/smhw-ember-engines-demo/node_modules/tree-sync/index.js:50:14)
    at Class.copyToOutputPath (/Users/miguelcamba/code/engines-demos/smhw-ember-engines-demo/node_modules/ember-cli/lib/models/builder.js:153:10)
    at /Users/miguelcamba/code/engines-demos/smhw-ember-engines-demo/node_modules/ember-cli/lib/models/builder.js:167:21
```

**Comment by mike-north** [comment] 2016-11-22 11:20
I regularly get `ENOTEMPTY` issues within the `dist/node_modules` folder. I believe that this part of the problem is a fastboot issue, not an engines issue.

I suspect that the core issue you raised has to do with building the fastboot asset map for lazy engines. I took a look at @nathanhammond's [lazy engine testing repo](https://github.com/nathanhammond/lazy-engine-testing) but it hasn't been updated in a while and is no longer working (needs to use the normal `ember-resolver` and a few other changes).

**Comment by stefanpenner** [comment] 2016-11-22 14:18
> I regularly get ENOTEMPTY issues within the dist/node_modules folder. I believe that this part of the problem is a fastboot issue, not an engines issue.

I think we have a solution to this in Fastboot:

1. primarily don't serve from dist

**Comment by mike-north** [comment] 2016-11-23 11:56
Now I'm seeing an error with eager engines in fastboot
```
There was an error trying to run your application in FastBoot.

This is usually caused by either your application code or an addon trying to access an API that isn't available in Node.js.
Based on the stack trace, it looks like the exception was generated in dist/fastboot/engines-in-fastboot.js on line 87.
The exception is probably coming from your app. Look at this file and line number to determine what is triggering the exception.

The full stack trace is:

Failed to load asset manifest. For browser environments, verify the meta tag with name "engines-in-fastboot/config/asset-manifest" is present. For non-browser environments, verify that you included the node-asset-manifest module.
Error: Failed to load asset manifest. For browser environments, verify the meta tag with name "engines-in-fastboot/config/asset-manifest" is present. For non-browser environments, verify that you included the node-asset-manifest module.
```

It should be reproducible with this project
https://github.com/mike-north/bug-engines-in-fastboot

which has the following general setup
```sh
/app       # host application
/lib/blog  # eager blog engine
/lib/uikit # in-repo-addon that contains a component, consumed by both the engine and host app 
```
For specific package versions, check out [yarn.lock](https://github.com/mike-north/bug-engines-in-fastboot/blob/master/yarn.lock)
###### versions
```yaml
ember-cli: 2.10.0-beta.2
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
os: darwin x64
```

**Comment by trentmwillis** [comment] 2016-11-23 16:16
@mike-north sounds like you need to load the `node-asset-manifest` into the FastBoot sandbox ([similar to how the app is loaded here](https://github.com/ember-fastboot/fastboot/blob/946bb882947999154e210c2df843a9414f51f63f/src/ember-app.js#L123-L146)). However, I don't believe there is a public API do that yet (I hear it is being worked on).

**Comment by josemarluedke** [comment] 2017-05-05 16:51
Has anyone successfully used FastBoot and lazy engines?

**Comment by egaba88** [comment] 2017-06-17 21:28
to keep engines set up with your project but still are waiting for a solution for this is to turn off asset manifest generation during build
```
/* ember-cli-build.js */
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    assetLoader: {
      noManifest: true
    }

// codez
```

**Comment by rwwagner90** [comment] 2017-09-10 23:11
My engine is not lazy, but still blows up with fastboot. Anyone have a fix?

**Comment by villander** [comment] 2019-10-26 17:35
@dgeb @rwjblue can you close this, please?

**Comment by rwwagner90** [comment] 2019-10-26 17:37
@villander is it fixed?

**Comment by villander** [comment] 2019-10-26 17:40
@rwwagner90 yet, at least 1 year. We have all support of Fastboot on lazy and eager engines to route and routeless engines ; )

**Comment by rwwagner90** [comment] 2019-10-27 00:12
@villander nice! I need to try engines out again. I haven't used them in years.

**Comment by villander** [comment] 2019-10-27 16:09
Definitely you need 😅. Feel free to reach out to me on Discord if you have any questions

**Closed** 2019-10-30 13:17 UTC
