### ISSUE TITLE
Adding models to a parent engine's `store`.

### ISSUE THREAD

**Issue by nathanhammond** [ember-engines/ember-engines#106] opened 2016-05-11 21:25 UTC
So let's say you're in `child-engine` with this dependency chain:

``` javascript
dependencies: {
  services: [
    'store'
  ]
}
```

The `store` that is passed in is effectively in `parent-engine`'s scope. If `child-engine` wishes to _extend_ `parent-engine`'s `store` with additional available models that is presently only possible by abusing the `app` folder inside of `child-engine`.

We need to define a pattern for this behavior as it is almost guaranteed to be an issue.

/cc @kaceykaso @jwlawrence @cklimkowsky @trentmwillis

**Comment by runspired** [comment] 2016-05-11 21:52
I believe this gets resolved auto-magically with the new modules unification proposal.

**Comment by trentmwillis** [comment] 2016-05-12 00:19
The idea of "extending" something that is shared with the `parent-engine` (such as the store) is really more a form of "reopening" which has the potential to lead to race conditions and order-dependent behavior between sibling Engines.

That said, the primary reason for wanting this behavior is two fold:

1. Re-exporting all the shared models from `parent-engine` into `child-engine` is a chore, and
2. If certain models (read, data) have already been loaded in `parent-engine` you don't want to refetch them in `child-engine`.

The first issue is solvable via better tooling (e.g., `EngineAddon` which auto-magically does those re-exports). The second issue, however, is a bit more difficult, but I don't think reopening the host `store` is the proper way to solve it.

In essence what I think should probably happen, is that `child-engine` should have its own instance of `store` with the additional models and importing all the needed models from a shared addon that `parent-engine` uses as well. We then need to make `store` Engine-aware in such a way that it will check for state in `parent-engine` before attempting to retrieve that same info from the server. This might be as simple as specifying a "parent" store for the `child-engine`'s `store` instance.

@runspired I haven't had time to read the new modules proposal yet, what part of it might solve this?

**Comment by buschtoens** [comment] 2016-05-12 02:28
What a coincidence that I also just ran into this issue. :smile: 

I'd just like to add that besides models we'd also need support for adapters & serializers. It would be pretty neat if I could define an `application` (or `engine`) adapter that would work just like the traditional `application` adapter, but scoped / limited to the models provided by the engine.

**Comment by eccegordo** [comment] 2016-10-10 09:43
Can someone explain with engines today is it possible to have its own store? 

@trentmwillis comment above suggests otherwise.

The use case I am trying out is building an admin engine for basic CRUD operations (think rails admin)

In my scenario it is assumed that the "admin" engine could be run under two logical scenarios:

1) mounted in a parent host app with same model (say 'user') defined in both parent and engine
- two stores
- two user model (with same exact definition)
 
2) Independently of a parent app either as standalone or just mounted in some generic do nothing parent app. 
- one store (inside engine)
- one user model (inside engine)

**Comment by nathanhammond** [comment] 2016-10-10 19:17
@eccegordo Totally possible, just don't pass down the store service and it's a shared-nothing story. This likely has edge cases that we haven't encountered yet.

**Comment by eccegordo** [comment] 2016-10-10 20:59
@nathanhammond Thanks. Was trying engines out and hit the `findAll not a function` bug

https://github.com/dgeb/ember-engines/issues/218

Not sure if there is something I was missing with the addon structure conventions and trying this inside the dummy app, but wasn't obvious to me. Will share a repo if I can reproduce.

**Comment by jwlawrence** [comment] 2016-11-22 21:47
Any updates on the approach outlined by @trentmwillis ?

Currently, I am getting around this by including all models in a shared addon and relying on the parent app's store. In an attempt to keep models separated by engine, I'm toying with the idea of using the parent app's store only for shared models (user/auth data, etc) and injecting it into all of my engines as 'globalStore'. Then each engine could have it's own separate store scoped only to the models it defines.

Not sure if this approach will work or not, so I wanted to see if there was any progress here before I give it a shot.

**Comment by peStoney** [comment] 2016-11-24 09:20
@nathanhammond I was following the hint you gave @eccegordo but still there's just the legacy store object mentioned in [#218](https://github.com/dgeb/ember-engines/issues/218). Looks like something's missing (?)

Besides that is there any way to define a model inside an engine that is added to the parent app's store?

**Comment by fr0gs** [comment] 2017-09-08 14:30
@nathanhammond @eccegordo I am experiencing the same issue, I have models in the engine that are never to be used in the parent app. The parent's app.js is like this:

```js
App = Ember.Application.extend({
  modulePrefix: config.modulePrefix,
  podModulePrefix: config.podModulePrefix,
  Resolver,
  engines: {
    emberStackBuilderEngine: {
      }
    },
});

the engine.js like: 

```js
const { modulePrefix } = config;
const Eng = Engine.extend({
  modulePrefix,
  Resolver
});

loadInitializers(Eng, modulePrefix);
export default Eng;
```

I want isolation from the engine's model to parent's, but I keep getting this error:

```
ember.debug.js:18023 TypeError: Cannot read property 'router' of undefined
    at error (ember.debug.js:28951)
    at Router.triggerEvent (ember.debug.js:29132)
    at trigger (ember.debug.js:56465)
    at Transition.trigger (ember.debug.js:57007)
    at ember.debug.js:56815
    at tryCatch (ember.debug.js:59077)
    at invokeCallback (ember.debug.js:59092)
    at publish (ember.debug.js:59060)
    at publishRejection (ember.debug.js:58995)
    at ember.debug.js:38900
    at invokeWithOnError (ember.debug.js:346)
    at Queue.flush (ember.debug.js:405)
    at DeferredActionQueues.flush (ember.debug.js:529)
    at Backburner.end (ember.debug.js:599)
    at ember.debug.js:1165
```

As if it is no longer able to mount the engine.

**Comment by villander** [comment] 2019-10-28 16:09
I talked with @runspired about it, they're working on that and it's not an engines problem
**it's an ember-data problem**, there's nothing engines can do to help but it's also low priority because models are on the way out.

can we close this one, please?

cc: @dgeb @rwjblue

**Closed** 2019-10-29 18:25 UTC

**Comment by mvrkljan** [comment] 2020-04-10 15:51
@villander any chance you could point to a ticket in ember data repo where the related issue can be tracked? Thank you!

**Comment by villander** [comment] 2020-04-10 15:53
@runspired can you point it here, buddy? please

**Comment by Leooo** [comment] 2020-05-22 15:27
@villander @runspired , I second @mvrkljan in asking for a link to follow the related issues in ember-data, before closing such thread please.

We are also looking for a way to have engines declare their own models while still persisting parent app's store / models.
